services:
  hugo:
    image: hugo:debiantrixie
    command: tail -f /dev/null
    ports:
      - "1313:1313"
    volumes:
      - "${PWD}/hugo:/home/hugo"
    environment:
      - USERID=${USERID:-530800011}
      - GROUPID=${GROUPID:-530800011}
